### PR TITLE
🚜 refactor:

### PR DESCRIPTION
**Pull request by wilmer162000**
- Fixed overflow backdrop blur in nav bar
- Removed top padding in nav bar

### CODE REVIEW

**Comment by DDuran19** [comment]
I will post my review here later

**Review by DDuran19 — CHANGES_REQUESTED** [review]
Checkout may latest comment

**Comment by devpapi0891** [comment]
To make the text more readable.

I suggest making the navbar background a solid color when in NIGHT MODE. 
Or
if it will work by increasing or decreasing the intensity of the blur effect when in NIGHT MODE

image

**Comment by directormac** [comment]
@wilmer162000

**Comment by DDuran19** [comment]
@wilmer162000  I have created a new commit concerning some fixes for the navbar, for now let us focus on the readability of the text kindly run the code below to get the latest version, thank you!

```bash
git pull origin main

```

**Pull request closed without merging**
