### PR TITLE
#8 Projects Section Component

### PR DESCRIPTION
**Pull request by DenverBrian**
- [x] create cards project
- [x] display cards using carousel
- [ ] mobile responsive
- [ ] show cards definition when hover

### CODE REVIEW

**Comment by DDuran19** [comment]
I'm gonna be reviewing this

**Comment by DDuran19** [comment]
image
 is this good for merging already? I'll wait for all checkbox to be checked. also kindly run 
 ```sh
 pnpm format && pnpm lint
 ```
 BEFORE pushing to avoid the CI/Lint error @DenverBrian 
 
image

**Comment by DenverBrian** [comment]
noted on running the pnpm format && pnpm lint 
about the project section I'm trying to re create it again from scratch using [Embla Carousel](https://www.embla-carousel.com/)

**Comment by DDuran19** [comment]
> noted on running the pnpm format && pnpm lint about the project section I'm trying to re create it again from scratch using [Embla Carousel](https://www.embla-carousel.com/)

if you need help let us know

**Pull request closed without merging**
