### PR TITLE
#86 Jellyfish/registration page

### PR DESCRIPTION
**Pull request by Frostzeichen**
This PR adds new functionality for the checkbox, radio, and file types in the eventRequirements factory.

The changes are as follows:
- Checkbox and radio will allow adding new choices into the fields.
- File contains a visible label to allow users to see the instructions.

These changes were used to build parts of the registration page.

### CODE REVIEW

**Comment by DDuran19** [comment]
Kindly run 
```sh
pnpm format && pnpm lint
```

to ensure that there'll be no linting issue prior to pushing

**Review by DDuran19 — CHANGES_REQUESTED** [review]
image

- [ ] Modify subtitle and description props
- [ ] On Register.svelte, kindly increase gap between title and subtitle because g is touching the subtitle below
- [ ] Make the"Event Details" portion customizable from outside. (export let). it should not appear on /register
- [ ] eventDetails should be empty on /register

**Comment by Frostzeichen** [comment]
Got it. Seems like pnpm lint returns the following error:

> > daedalus.codes@0.0.2 lint /home/terenzjomar/Daedalus/daedalus-codes-landing
> > prettier  --check src/* && eslint .
> 
> Checking formatting...
> All matched files use Prettier code style!
> 
> /home/terenzjomar/Daedalus/daedalus-codes-landing/src/lib/components/events/Register.svelte
>     3:9  error  'CardsCourses' is defined but never used  @typescript-eslint/no-unused-vars
>   122:6  error  `{@html}` can lead to XSS attack          svelte/no-at-html-tags
> 
> ✖ 2 problems (2 errors, 0 warnings)
> 
>  ELIFECYCLE  Command failed with exit code 1.

**Comment by Frostzeichen** [comment]
Should I try fixing these? I'm not quite sure what to do though

**Comment by DDuran19** [comment]
> Got it. Seems like `pnpm lint` returns the following error:

kindly fix by removing those unused variables. I also added  some todos for changes

**Comment by Frostzeichen** [comment]
> > Got it. Seems like `pnpm lint` returns the following error:
> 
> kindly fix by removing those unused variables. I also added some todos for changes

Alright, I'll work on them asap!

**Comment by DDuran19** [comment]
> Should I try fixing these? I'm not quite sure what to do though

Yes, it says 

> /Register.svelte
3:9 error 'CardsCourses' is defined but never used

which means that on line 3, 9th character, CardsCourses were defined but never used. You have to delete the definition

**Comment by DDuran19** [comment]
@directormac  do we have someone assigned in making the api route where the data for these forms will be delivered?

**Comment by Frostzeichen** [comment]
**Current Progress:**
**Register.svelte**
- [ ] On Register.svelte, kindly increase gap between title and subtitle because g is touching the subtitle below
- [ ] Make the"Event Details" portion customizable from outside. (export let). it should not appear on /register
- [ ] Deal with the lint error at 3:9
- [ ] Deal with the lint error at 122:6

**+page.svelte**
- [ ] Modify subtitle and description props
- [ ] eventDetails should be empty on /register

**Comment by Frostzeichen** [comment]
@DDuran19 I've finished the changes. There's a problem with `pnpm run check` though, seems like a problem with the utils/CardsProjects component.

Does the Register component depend on this component somewhere down the line?

Also, nice job with the tests. That thing looks _sleek_!

**Comment by Frostzeichen** [comment]
Forgot to add this in:

Changelog
- Adds bottom margin for eventTitle.
- When eventDetails.length is 0, the Event Details section will not show.
- Removes @html tag from 122:6 (now 123:6 post-edit) which causes eslint to return an error (makes the code prone to XSS attacks).
	- This change doesn't seem to do much. But if it breaks anything, let me know and I'll find a better fix.
- Subtitles and event description now have new text. They were written for the context of a general registration page for people joining Daedalus.
	- I added emojis since I liked the way the original version looked.
	- Let me know if you think these descriptions seem lacking. I'll edit them right away.

**Comment by DDuran19** [comment]
Good job with the consistent PR and you were able to address everything.

- [ ] not very major, but can we choose a different emoji
- [ ] style: "cursor: pointer" on input type: "file" (upload picture)

**Comment by Frostzeichen** [comment]
Late reply, sorry. Working on it now!

**Current progress:**
- [ ]  not very major, but can we choose a different emoji
- [ ] style: "cursor: pointer" on input type: "file" (upload picture)

**Comment by Frostzeichen** [comment]
@DDuran19 done with the edits! I think the sun emoji kind of fits better than the fire and wing emoji pair. But I'm not sure if it's good enough. What do you think?

**Pull request merged**
